"""init

Revision ID: a67a71b255b3
Revises: 949cab9c6e12
Create Date: 2022-03-08 19:33:13.986697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67a71b255b3'
down_revision = '949cab9c6e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example', sa.Column('maia', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('example', 'maia')
    # ### end Alembic commands ###
