from os import getenv


ENVIRONMENT = getenv("ENVIRONMENT")
DATABASE_HOST = getenv("DATABASE_HOST")
DATABASE_USER = getenv("DATABASE_USER")
DATABASE_PASS = getenv("DATABASE_PASS")
DATABASE_DB = getenv("DATABASE_DB")
DATABASE_PORT = getenv("DATABASE_PORT", 5433)

ORIGINS = ["*"]
